### ISSUE TITLE
constants.js refactor

### ISSUE THREAD

**Issue by hkiame** [melcor76/js-tetris#10]
Hi,

I was going through the code and in constants.js i saw that it would be neat to have the the Object.freeze been called at a single place i.e. having an array of the items that need to be freezed then run a forEach loop calling the Object.freeze method. I would love to do this if you find it helpful.

**Comment by melcor76** [comment]
Hi @hkiame,

Sure you should do it! I love getting improvements to the code and that sounds interesting.

**Comment by hkiame** [comment]
Awesome!
